# This file is part of level.
# https://github.com/heynemann/level

# Licensed under the MIT license:
# http://www.opensource.org/licenses/MIT-license
# Copyright (c) 2016, Bernardo Heynemann <heynemann@gmail.com>

language: python

python:
    - "3.4"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
