language: go

go:
  - 1.6.2

sudo: required

services:
  - redis

install:
  - make setup
  - go get github.com/mattn/goveralls

script:
  - make test-coverage

after_success:
  - $HOME/gopath/bin/goveralls -coverprofile _build/test-coverage-all.out -service=travis-ci
  #- ./push_to_docker.sh
  #- curl -H POST $TEST_FARM_URL
